In [1]:
import numpy as np
import healpy as hp

/Users/yoachim/lsst/DarwinX86/miniconda2/3.19.0.lsst4/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [7]:
ack = np.array([[1,2,3,4], [2,3,4,5], [3,4,5,6]] )

In [8]:
ack

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [9]:
a = np.array([3,3,3])

In [14]:
np.searchsorted(ack[1,:], a[0])

1

In [15]:
def ss_split(arr, side='left'):
    """
    make it possible to run searchsorted easily on 2 dims
    """
    result = np.searchsorted(arr[1:], arr[0], side=side)
    return result

In [27]:
temp_array = np.column_stack((a,ack))
np.apply_along_axis(ss_split, 1, temp_array)

array([2, 1, 0])

In [28]:
np.apply_along_axis(ss_split, 1, temp_array, side='right')

array([3, 2, 1])